apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centos
        image: centos
        command: ["sh", "-c", "while true; do echo Hello AKS; sleep 3600; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: centos-service
spec:
  selector:
    app: centos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
